# Generated by Django 6.1.1 on 2026-09-21 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('bus_model', models.CharField(max_length=100)),
                ('bus_contractor', models.CharField(max_length=100)),
                ('current_longitude', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['route_name'],
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitors', to='bus_tracker_app.route')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('configured_leg1_arrival', models.TimeField()),
                ('configured_leg2_arrival', models.TimeField()),
                ('assigned_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stops', to='bus_tracker_app.route')),
            ],
            options={
                'ordering': ['assigned_route__route_name', 'descriptor'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('assigned_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='bus_tracker_app.stop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='bus_tracker_app.route')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='bus_tracker_app.bus')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='bus_tracker_app.monitor')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='bus_tracker_app.route')),
                ('students', models.ManyToManyField(blank=True, related_name='trips', to='bus_tracker_app.student')),
            ],
            options={
                'ordering': ['-date', 'route__route_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='bus_tracker_app.student')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='bus_tracker_app.trip')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('assigned_route', 'descriptor'), name='unique_stop_per_route'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('route', 'date'), name='one_trip_per_route_day'),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'trip'), name='one_attendance_record_per_student_trip'),
        ),
    ]
