# Generated by Django 6.1.1 on 2026-09-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracker_app', '0005_trip_stop_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='leg',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Morning'), (2, 'Afternoon')]),
        ),
    ]
